### ISSUE TITLE
Failed to get license. Reason: No license is allocated in floating license server.

### ISSUE THREAD

**Issue by ramana152** [evryfs/readyapi#2]
Hello team,

    Am getting error while creating docker container for ReadyAPI, Here am attaching screenshot please find it.
    Please provide me the solution , How to activate the ReadyAPI license for Docker step by step.
![ReadyAPI error](https://user-images.githubusercontent.com/39365142/71579766-0f13e300-2b24-11ea-957c-2a3c2c8d4e62.PNG)

**Comment by mohanaraosv** [comment]
@ramana152  This docker image requires ReadyApi license, Do you have the software license exist scripts work only Evry networks.

**Comment by davidkarlsen** [comment]
set the env var `LICENSE_SERVER` to point to the license-server.
Note that Smartbear provides official images: https://hub.docker.com/r/smartbear/ready-api-soapui-testrunner/

<blockquote><div><strong><a href="https://hub.docker.com/r/smartbear/ready-api-soapui-testrunner/">Docker Hub</a></strong></div></blockquote>
